-- Databricks notebook source
-- DDL for step 1
CREATE OR REPLACE TABLE `gdsi-oncanaloglib`.HV_PAT_UNIVERSE_CLN
(HV_ID VARCHAR(1000),
TUMOR_GROUP VARCHAR(100),
SOURCE VARCHAR(10),
VERSION_KEY INT)

-- COMMAND ----------

-- INSERT INTO `gdsi-oncanaloglib`.HV_PAT_UNIVERSE_CLN (HV_ID, TUMOR_GROUP, SOURCE,VERSION_KEY)
-- VALUES ('pat_id', 'test', 'test', 0);

-- COMMAND ----------

-- DDL for step 2
CREATE OR REPLACE TABLE `gdsi-oncanaloglib`.HV_CLAIMS_UNIVERSE_CLN
(CLAIM_ID VARCHAR(10000),
HV_ID VARCHAR(10000),
DATE_SERVICE DATE,
DAIGNOSIS_CODE VARCHAR(10000),
DAIGNOSIS_PRIORITY VARCHAR(10000),
PROCEDURE_CODE VARCHAR(10000),
NDC_CODE VARCHAR(10000),
DISPENSED_QUANTITY VARCHAR(10000),
DAYS_SUPPLY VARCHAR(10000),
TUMOR_GROUP VARCHAR(10000),
SOURCE VARCHAR(10000))

-- COMMAND ----------

-- DDL for step 3
CREATE OR REPLACE TABLE `gdsi-oncanaloglib`.REGIMEN_OUTPUT_DF
(TUMOR VARCHAR(1000),
REGIMEN VARCHAR(1000),
YR_MNTH VARCHAR(1000),
LoT VARCHAR(1000),
Regimen_Start VARCHAR(100),
BIOMARKER VARCHAR(1000),
PATIENT_SEGMENT VARCHAR(1000),
AnalogMoleculeName VARCHAR(1000),
REGIMEN_DAYS VARCHAR(1000))

-- COMMAND ----------


